[package]
name = "riff-plugin-thelineofbestfit"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
editorial-common = { path = "../editorial-common" }
extism-pdk = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
